travis:
  secure:
    BINSTAR_TOKEN: VbsceniCTAsvBPUPOUwSW/MhzkWJXNJ3U+g1YZ2o8nVH/+YmA29kKOjeTVuQ6MAruwVOxe5iAXUhMFc12cRKlHJ3gN/5No+ehFV4jmWWwJEtnzek/IZ+fvFis7HjGL9B0pWq0QvmuDYFZ7pV3ZXG9jtr30lhKxddox7gAUruwUOp7avUtfVf2qtbOQdKyhrWXlzBqXyzx1EqsGOGXMRewDPMVPVL0F1wI7hUq/ysO0ZRONt/bnRayWEHYqSQ55aJXbojqOv83YVZf5ArJj4VpYEwL7aTUI00x2JPVUxDufMQl3adi3Tnb25JIY0yBmPYdBSy/PiKb7eQygYAtAvG2no0bpgR3NXChwSIujGMinjQfxAd7y5h7iitDS+Z4sOoDuTwKFE3Kq00FpU7K6kVJGnBiS/gRWRa/WljcdKPyGMzntANhqUCW/DIawRrR/DsOqAG+fWpNM8uQu7yKHK95VQhcPAnbHGferDqpfSrtz8GL0WHWz0hOyf1v41yLv3IsrNDhi8eCllzLa51BEhotmGLv2jcOAzX3Pa9eVAK0TxiEzI7mxdeCemtowu8SCLkuIXmbCrVH8S92G4ZMogHEPmK76XvQ7IY1anlLaGPLneqp0t6TImg/CgXQLCVMLp003r1oSDl90C2/hrWdkYg9VlBCysYgrdfu7PMnmxqfg0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
